name:                METAR
version:             0.1.0.0
github:              "flskif/METAR"
license:             BSD3
author:              "Alex K"
maintainer:          "flskif@gmail.com"
copyright:           "2018 Alex K"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/flskif/METAR#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- bytestring
- attoparsec

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-exported-signatures
  - -Wmissing-import-lists
  - -Widentities
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  metar:
    main:                Main.hs
    source-dirs:         app/metar
    dependencies:
    - METAR
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  metar-generate:
    main:                Main.hs
    source-dirs:         app/metar-generate
    dependencies:
    - METAR
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  metar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - METAR
    - tasty
    - tasty-hspec
